# Generated by Django 3.2.25 on 2026-06-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_no', models.AutoField(db_column='member_no', primary_key=True, serialize=False)),
                ('member_id', models.CharField(db_column='member_id', max_length=20, unique=True)),
                ('member_pwd', models.CharField(db_column='member_pwd', max_length=200)),
                ('member_name', models.CharField(db_column='member_name', max_length=50)),
                ('member_email', models.CharField(db_column='member_email', max_length=50)),
                ('usage_flag', models.CharField(db_column='usage_flag', default='1', max_length=10)),
                ('register_date', models.DateTimeField(auto_now_add=True, db_column='register_date')),
                ('access_latest', models.DateTimeField(blank=True, db_column='access_latest', null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suwontrash_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_column='date', max_length=50)),
                ('total', models.CharField(db_column='total', max_length=50)),
                ('key_num', models.ForeignKey(db_column='key_num', on_delete=django.db.models.deletion.CASCADE, related_name='connect', to='member.member')),
            ],
            options={
                'db_table': 'suwontrash_all',
            },
        ),
    ]
