# Generated by Django 3.2.25 on 2026-06-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('admin', '관리자'), ('member', '일반회원')], db_column='role', default='member', max_length=20),
        ),
    ]
