# Generated by Django 3.2.25 on 2026-06-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facility',
            field=models.CharField(blank=True, choices=[('', '해당없음'), ('강남', '강남 자원회수시설'), ('노원', '노원 자원회수시설'), ('마포', '마포 자원회수시설'), ('양천', '양천 자원회수시설')], db_column='facility', default='', max_length=20),
        ),
    ]
